language: php
dist: xenial
php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4snapshot

install:
    - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --no-interaction; fi
    - if [ "$dependencies" = "highest" ]; then composer update --no-interaction; fi

script:
    - make test
    - make phpstan

after_script:
    - npx @cedx/coveralls build/coverage/clover.xml

env:
    matrix:
        - dependencies=lowest
        - dependencies=highest
