services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Isocontent\:
        resource: '../../../../../'
        exclude: '../../{DependencyInjection,IsocontentBundle.php}'


    Isocontent\Isocontent:
        public: true
        arguments:
            $parsers: !tagged isocontent.parser
            $renderers: !tagged isocontent.renderer

    isocontent: '@Isocontent\Isocontent'

